// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Edu_NSW_ACT_Foundation } from 'next/font/google';

const eduFont = Edu_NSW_ACT_Foundation({
  weight: ['400'], // or '500', '700' depending on the look you want
  subsets: ['latin'],
  variable: '--font-sketchy',
});

export const metadata: Metadata = {
  title: "Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" className={eduFont.variable}>
        <body>
          <header>
          </header>
          {children}
        </body>
      </html>
  );
}
